apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
    env: {{.Release.Namespace}}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
  name: {{.Values.name}}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
      env: {{.Release.Namespace}}
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        env: {{.Release.Namespace}}
    spec:
    {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: application
          image: {{.Values.imageName}}
          imagePullPolicy: Always
        {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 10 }}
        {{- end }}

          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.readinessProbe}}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources}}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
              name: {{.Values.service.name}}

      {{- if .Values.sidecarContainers }}
{{ toYaml .Values.sidecarContainers | indent 6 }}
      {{- end}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
