pipeline {
    agent {
        kubernetes {
            label 'build-agent'  // This should match the label defined in your pod template
        }
    }
    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = 'your-ecr-repo-url'
        IMAGE_TAG = "sample-node-app:${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Lint') {
            steps {
                sh 'yamllint k8s/'
            }
        }
        stage('Test') {
            steps {
                dir('app') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("$IMAGE_TAG", './app')
                }
            }
        }
        stage('Push to ECR') {
            steps {
                echo 'Simulate push to ECR or implement AWS CLI commands here'
            }
        }
        stage('Deploy to EKS') {
            steps {
                echo 'Simulate deploy to EKS or run kubectl apply'
            }
        }
    }
        post {
            success {
                    echo "Deployment Success!"
                    slackSend(teamDomain: 'team-domain',
                            tokenCredentialId: 'slack-jenkins-id',
                            baseUrl: 'https://<team-domain>.slack.com/services/hooks/jenkins-ci/',
                            channel: '#jenkins',color: '#e34234',
                            message: "${MS_NAME} has been deployed to env ${env.BRANCH_NAME}")    
            }
            failure {
                    echo "Deployment Failed!"
                    slackSend(teamDomain: 'team-domain',
                            tokenCredentialId: 'slack-jenkins-id',
                            baseUrl: 'https://<team-domain>.slack.com/services/hooks/jenkins-ci/',
                            channel: '#jenkins',color: '#e34234',
                            message: "Deployment Failed! ${MS_NAME} to env ${env.BRANCH_NAME}")    
            }		
        }
}
