
replicas: 1
service:
  name: http
  port: 8000
  targetPort: 8000
labels:
  jobs: ShutdownStartup
resources:
  limits:
    cpu: 300m
    memory: 250Mi
  requests:
    cpu: 300m
    memory: 250Mi
name: my-node-js-app
imageName: <image-name>
